entrada = float(input("Entrada: "))
#Meu jeito
print("{} X 1: {}".format(entrada, entrada * 1))
print("{} X 2: {}".format(entrada, entrada * 2))
print("{} X 3: {}".format(entrada, entrada * 3))
print("{} X 4: {}".format(entrada, entrada * 4))
print("{} X 5: {}".format(entrada, entrada * 5))
print("{} X 6: {}".format(entrada, entrada * 6))
print("{} X 7: {}".format(entrada, entrada * 7))
print("{} X 8: {}".format(entrada, entrada * 8))
print("{} X 9: {}".format(entrada, entrada * 9))
print("{} X 10: {}\n".format(entrada, entrada * 10))
#Guanabara
print("-" * 20)
print("{} X {:2}: {}".format(entrada, 1, entrada * 1))
print("{} X {:2}: {}".format(entrada, 2, entrada * 2))
print("{} X {:2}: {}".format(entrada, 3, entrada * 3))
print("{} X {:2}: {}".format(entrada, 4, entrada * 4))
print("{} X {:2}: {}".format(entrada, 5, entrada * 5))
print("{} X {:2}: {}".format(entrada, 6, entrada * 6))
print("{} X {:2}: {}".format(entrada, 7, entrada * 7))
print("{} X {:2}: {}".format(entrada, 8, entrada * 8))
print("{} X {:2}: {}".format(entrada, 9, entrada * 9))
print("{} X {:2}: {}".format(entrada, 10, entrada * 10))
print("-" * 20)
